spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: securityDemo
    password: securityDemo

mybatis:
  config-location: classpath:mybatis-config.xml


