POST http://localhost:8080/formLogin
Content-Type: application/json

{ "username" : "admin" ,"password":"admin"}

### admin

POST http://localhost:8080/formLogin
Content-Type: application/json

{"username" : "user" ,"password" : "user"}

### user

POST http://localhost:8080/formLogin
Content-Type: application/json

{"username" : "empty" , "password" : "empty"}

### empty